### ISSUE TITLE
Needs to be too wide on desktop before view switches

### ISSUE THREAD

**Issue by OJFord** [FelixOnline/FelixOnline#257]
Please change `small-max` and `medium-min` such that when the browser occupies 2/3 of a Macbook Air screen (957px wide) it doesn't look like a ridiculously oversized mobile :)

This number comes from using Spectacle.app to fill 2/3 screen with Chrome - I almost never have it full-screen.

This wouldn't be so exaggeratedly bad if the leading image weren't full width. Preferable - even on mobile, in my opinion - would be adding something like:
```css
.article-info-box{
    width: 49.5%;
    float: left;
}
.article-share{
    width: 49.5%;
    float: right;
}

.article-image,
#imgCont{
    float: left;
    width: 50%;
    margin-right: 1rem;
}
.article-row .article-image,
.article-row #imgCont{
    margin-bottom: 0;
}
.article-image-image{
    float: left;
}

blockquote{
    display: flex;
}
```
